% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name shift_right
%  @associatedFile /MATLAB Drive/shift_right.m
%  @mostRecentlyActioned true
%  @uniqueId DFE249B7

shift_right

%% @name is_overtime
%  @associatedFile /MATLAB Drive/is_overtime.m
%  @mostRecentlyActioned true
%  @uniqueId 9F7034E1

is_overtime

%% @name is_overtime_2
%  @associatedFile /MATLAB Drive/is_overtime.m
%  @mostRecentlyActioned false
%  @uniqueId 4A3D7628

is_overtime(hours)

%% @name ispythag
%  @associatedFile /MATLAB Drive/ispythag.m
%  @mostRecentlyActioned true
%  @uniqueId 80510049

ispythag

%% @name ispythag_2
%  @associatedFile /MATLAB Drive/ispythag.m
%  @mostRecentlyActioned false
%  @uniqueId 58141750

ispythag(a, b, c)

%% @name isdivby4
%  @associatedFile /MATLAB Drive/isdivby4.m
%  @mostRecentlyActioned true
%  @uniqueId 0A1EAEF1

isdivby4

%% @name isdivby4_2
%  @associatedFile /MATLAB Drive/isdivby4.m
%  @mostRecentlyActioned false
%  @uniqueId 62223902

isdivby4(inarg)

%% @name switch
%  @associatedFile /MATLAB Drive/switch.m
%  @mostRecentlyActioned true
%  @uniqueId 027E5F9B

switch

%% @name pickone
%  @associatedFile /MATLAB Drive/pickone.m
%  @mostRecentlyActioned true
%  @uniqueId 354E3A9C

pickone

%% @name my_cumsum
%  @associatedFile /MATLAB Drive/my_cumsum.m
%  @mostRecentlyActioned true
%  @uniqueId 5365C972

my_cumsum

%% @name corners
%  @associatedFile /MATLAB Drive/corners.m
%  @mostRecentlyActioned true
%  @uniqueId A9EEAEE2

corners

%% @name untitled
%  @associatedFile /MATLAB Drive/untitled.m
%  @mostRecentlyActioned true
%  @uniqueId B6B2272D

untitled

%% @name untitled_2
%  @associatedFile /MATLAB Drive/untitled.m
%  @mostRecentlyActioned false
%  @uniqueId 3BB2688D

untitled(x)

%% @name cumprod_vectors
%  @associatedFile /MATLAB Drive/cumprod_vectors.m
%  @mostRecentlyActioned true
%  @uniqueId 3C1ADDA5

cumprod_vectors

%% @name def2
%  @associatedFile /MATLAB Drive/def2.m
%  @mostRecentlyActioned true
%  @uniqueId 7FDFD68C

def2

%% @name def2_2
%  @associatedFile /MATLAB Drive/def2.m
%  @mostRecentlyActioned false
%  @uniqueId 27C304E8

def2(x)

%% @name def1
%  @associatedFile /MATLAB Drive/def1.m
%  @mostRecentlyActioned true
%  @uniqueId 14530893

def1

%% @name def1_2
%  @associatedFile /MATLAB Drive/def1.m
%  @mostRecentlyActioned false
%  @uniqueId 95711F3D

def1(x)

%% @name Trace
%  @associatedFile /MATLAB Drive/Trace.m
%  @mostRecentlyActioned true
%  @uniqueId 44CC00E6

Trace

%% @name Trace_2
%  @associatedFile /MATLAB Drive/Trace.m
%  @mostRecentlyActioned false
%  @uniqueId 5B935A02

Trace(A)

